ecommerce_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/logout/", views.LogoutView.as_view(), name="logout"),
    path("accounts/", include(("accounts.urls", "accounts"), namespace="accounts")),
    path("products/", include(("store.urls", "products"), namespace="products")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    path("detail/<int:pk>/", views.ProductDetailView.as_view(), name="detail"),
    path("list/", views.ProductListView.as_view(), name="list"),
    path("<int:pk>/add-to-cart/", views.AddToCartView.as_view(), name="add_to_cart"),
    path("cart-items/", views.CartView.as_view(), name="cart_view"),
    path("checkout/", login_required(views.CheckoutView.as_view()), name="checkout"),
    path(
        "remove-from-cart/<int:pk>/",
        views.RemoveFromCartView.as_view(),
        name="remove_from_cart",
    ),
    path(
        "order-detail/<int:pk>",
        views.OrderDetailView.as_view(),
        name="order_detail",
    ),
    path(
        "orders/",
        views.OrdersListView.as_view(),
        name="orders",
    ),
]

store/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

# class ProductManager(models.Manager):
#     def get_queryset(self):
#         return super(ProductManager, self).get_queryset().filter(in_stock=True)

"""
category/department: shoes, clothes etc
"""


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=7, decimal_places=2)
    category = models.ManyToManyField("store.Category", related_name="categories")
    # in_stock = models.BooleanField(default=True)
    # stock = models.IntegerField()

    # objects = models.Manager()
    # products = ProductManager()
    def __str__(self):
        return self.name

    def __repr__(self):
        return f"{self.__class__.__name__}: {self.name}"

    def get_absolute_url(self):
        return reverse("products:detail", kwargs={"pk": self.pk})


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def __repr__(self):
        return f"{self.__class__.__name__}: {self.name}"


class Image(models.Model):
    product = models.ForeignKey(
        "store.Product", related_name="product_image", on_delete=models.CASCADE
    )
    title = models.CharField(max_length=100)
    url = models.ImageField(upload_to="products")
    alt_text = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class Attribute(models.Model):
    name = models.CharField(max_length=100)
    product = models.ForeignKey(
        "store.Product", related_name="attribute_name", on_delete=models.CASCADE
    )
    # size = models.ForeignKey("app.Size", verbose_name=_(""), on_delete=models.CASCADE)
    # color = models.ForeignKey("app.Color", verbose_name=_(""), on_delete=models.CASCADE)

    def __repr__(self):
        return f"{self.__class__.__name__}: {self.name}"

    def __str__(self):
        return self.name


class AttributeValue(models.Model):
    value = models.CharField(max_length=100)
    attribute = models.ForeignKey(
        "store.Attribute", related_name="attribute_value", on_delete=models.CASCADE
    )

    def __repr__(self):
        return f"{self.__class__.__name__}: {self.value}"

    def __str__(self):
        return self.value


class OrderItem(models.Model):
    """ """

    customer = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )  # for identifying cart owner
    product = models.ForeignKey("store.Product", on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    is_placed = models.BooleanField(default=False)

    def __str__(self):
        return self.product.name

    def total(self):
        return self.quantity * self.product.price

    class Meta:
        ordering = ["-created_at"]


class Order(models.Model):
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    order_items = models.ManyToManyField("store.OrderItem")

    def get_order_total(self):
        total = 0
        for item in self.order_items.all():
            total += item.total()
        return total

    class Meta:
        ordering = ["-created_at"]


# Create your models here.
"""
Preliminary Field List

product name
product category
product expiry date
product description
product images
product price
product quantity
product rating
product colors

customer first name
customer last name
customer address
customer email
customer phone number 

order date placed
order total ($)
order item (product)
order number 
order delivery date
order delivery status 



"""

store/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, DetailView, ListView, TemplateView
from django.views import View
from .models import Product, Order, OrderItem
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.contrib import messages

# Create your views here.


class ProductDetailView(DetailView):
    template_name = "store/product_detail.html"
    model = Product
    context_object_name = "product"

    # def get_queryset(self):
    #     super().get_queryset()
    #     product = Product.objects.filter(pk=self.kwargs["pk"])
    #     return product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product_id = self.kwargs["pk"]
        print(f"product_id: {self.object.id}")
        product = Product.objects.get(pk=product_id)
        recently_viewed_products = None
        print(f"pr {self.object}")

        if "recently_viewed" in self.request.session:
            if product_id in self.request.session["recently_viewed"]:
                self.request.session["recently_viewed"].remove(
                    product_id
                )  # later for removing item from cart

            products = Product.objects.filter(
                pk__in=self.request.session["recently_viewed"]
            )
            recently_viewed_products = sorted(
                products,
                key=lambda x: self.request.session["recently_viewed"].index(x.id),
            )
            self.request.session["recently_viewed"].insert(0, product_id)
            if len(self.request.session["recently_viewed"]) > 4:
                self.request.session["recently_viewed"].pop()
        else:
            self.request.session["recently_viewed"] = [product_id]
        self.request.session.modified = True
        context["recently_viewed_products"] = recently_viewed_products
        return context


class ProductListView(ListView):
    model = Product
    template_name = "store/product_list.html"
    context_object_name = "products"

    def get_queryset(self):
        # Fetch the queryset from the parent get_queryset
        queryset = super().get_queryset()
        # Get the q GET parameter
        q = self.request.GET.getlist("category")
        print(q)
        if q:
            # Return a filtered queryset
            sess = self.request.session
            print(f"sess: {sess}")
            res = queryset.filter(category__name__in=q)
            print(f"res: {res}")
            return res
        # Return the base queryset
        return queryset


class AddToCartView(View):
    """
    if user is not logged in, item will be added to cart session using product_id.
    Once user logs in, items in session cart will be transferred to logged in user cart and
    session cart emptied.

    session cart should persist even after browser closure.

    """

    def get(self, request, *args, **kwargs):
        product_id = self.kwargs["pk"]
        product = Product.objects.get(pk=product_id)
        recently_viewed_products = None

        if self.request.user.is_authenticated:
            print("inside if user authenticated")
            # old_item = OrderItem.objects.get(
            #     customer=self.request.user, product=product
            # ) # this raises a DoesNotExit error if the object is not found and that causes
            old_item = OrderItem.objects.filter(
                customer=self.request.user, product=product, is_placed=False
            ).first()
            print("***** .before if old_items:")
            if old_item:
                old_item.quantity += 1
                old_item.save()
            else:
                print("_-_-_ inside else: for new_items:")
                new_item = OrderItem.objects.create(
                    customer=self.request.user, product=product
                )
                new_item.save()

        elif "recently_added" in self.request.session:
            # if product_id in request.session["recently_added"]:
            #     request.session["recently_viewed"].remove(product_id) # later for removing item from cart

            # products = Product.objects.filter(pk__in=request.session["recently_added"])
            # recently_viewed_products = sorted(
            #     products, key=lambda x: request.session["recently_added"].index(x.id)
            # )
            self.request.session["recently_added"].insert(0, product_id)
            # if len(request.session["recently_viewed"]) > 5:
            #     request.session["recently_viewed"].pop()
        else:
            self.request.session["recently_added"] = [product_id]
            # return HttpResponseRedirect(reverse_lazy("products:cart"))

        self.request.session.modified = True

        # context = {
        #     "product": product,
        #     "recently_viewed_products": recently_viewed_products,
        # }
        # return render(request, "store/cart.html", context)
        message = "successfully added to cart"
        messages.info(self.request, message)
        return HttpResponseRedirect(reverse_lazy("products:cart_view"))


class RemoveFromCartView(View):
    def get(self, request, *args, **kwargs):
        product_id = self.kwargs["pk"]
        product = Product.objects.get(pk=product_id)
        recently_viewed_products = None

        if self.request.user.is_authenticated:
            item = OrderItem.objects.filter(
                customer=self.request.user, product=product
            ).first()
            if item:
                item.delete()
        elif "recently_added" in self.request.session:
            self.request.session["recently_added"].remove(product_id)
            self.request.session.modified = True
        else:
            return HttpResponseRedirect(reverse_lazy("products:list"))
        return HttpResponseRedirect(reverse_lazy("products:cart_view"))


class CartView(TemplateView):
    """
    if user is logged in, show user cart otherwise grab session cart
    """

    template_name = "store/cart.html"
    # def get(self, request, *args, **kwargs):
    #     # product_id = self.kwargs["pk"]
    #     # product = Product.objects.get(pk=product_id)
    #     # recently_viewed_products = None
    #     print(f"request.sessions: {self.request.session['recently_added']}:")
    #     if self.request.user.is_authenticated:
    #         print("CartView.get()")
    # old_item = OrderItem.objects.filter(
    #     customer=self.request.user, product=product
    # ).first()
    # if old_item:
    #     old_item.quantity += 1
    #     old_item.save()
    # else:
    #     new_item = OrderItem.objects.create(
    #         customer=self.request.user, product=product
    #     )
    #     new_item.save()

    #     for id in self.request.session["recently_added"]:
    #         print("CartView.get().if")
    #         prod = Product.objects.get(pk=id)
    #         if OrderItem.objects.filter(
    #             customer=self.request.user, product=prod
    #         ).first():
    #             self.request.session["recently_added"].remove(id)
    #         else:
    #             OrderItem.objects.create(customer=self.request.user, product=prod)
    #         request.session.modified = True
    # # elif "recently_added" in self.request.session:

    # #     self.request.session["recently_added"].insert(0, product_id)
    # # else:
    # # self.request.session["recently_added"] = [product_id]
    # print("outside for loop")
    # return render(self.request, "store/cart.html")

    # request.session.modified = True
    # return HttpResponseRedirect(reverse_lazy("products:cart_view"))

    def get_context_data(self, **kwargs):
        print("inside get_context_data")
        context = super().get_context_data(**kwargs)
        products = None
        recently_added_products = None
        if self.request.user.is_authenticated:
            context["user_cart"] = OrderItem.objects.filter(
                customer=self.request.user, is_placed=False
            )
            if "recently_added" in self.request.session:
                print(f" self.request.session {self.request.session['recently_added']}")
                if self.request.session["recently_added"]:
                    for id in self.request.session["recently_added"]:
                        print("for id in self.request.session['recently_added']:")
                        prod = Product.objects.get(pk=id)
                        if OrderItem.objects.filter(
                            customer=self.request.user, product=prod
                        ).first():
                            self.request.session["recently_added"].remove(id)
                        else:
                            OrderItem.objects.create(
                                customer=self.request.user, product=prod
                            )
                        print('about to delete "recently_added"')
                print(
                    f"before del request.session {self.request.session['recently_added']}"
                )
                del self.request.session["recently_added"]
                # print(
                #     f"after del request.session {[sess for sess in self.request.session]}"
                # )
                self.request.session.modified = True
        if "recently_added" in self.request.session:
            print("if recently_added:  ")
            products = Product.objects.filter(
                pk__in=self.request.session["recently_added"]
            )
        else:
            print('adding self.request.session["recently_added"]')
            self.request.session["recently_added"] = []
            # return context
        if products:
            recently_added_products = sorted(
                products,
                key=lambda x: self.request.session["recently_added"].index(x.id),
            )
        # request.session["recently_viewed"].insert(0, product_id)

templates/store/cart.html
{% extends 'base.html' %}

{% block content %}

    {% if user.is_authenticated %}
    <div class="bg-white">
        <div class="mx-auto max-w-2xl py-16 px-4 sm:py-24 sm:px-6 lg:px-0">
            <h1 class="text-center text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Shopping Cart</h1>
            <section aria-labelledby="cart-heading">
                <h2 id="cart-heading" class="sr-only">Items in your shopping cart</h2>
                
                <ul role="list" class="divide-y divide-gray-200 border-t border-b border-gray-200">
                    
                    {% if user_cart %}
                    {% for product in user_cart %}
                    <form class="mt-12">
                        <li class="flex py-6">
                            <form action="{% url 'products:list' %}" method="GET">
                                <div class="flex-shrink-0">
                                    {% with product.product.product_image.all|first as image%}
                                    <img src="{{ image.url.url }}" alt="{{ image.alt_text }}" class="h-24 w-24 rounded-md object-cover object-center sm:h-32 sm:w-32">
                                    {% endwith %}
                                </div>
                                
                                <div class="ml-4 flex flex-1 flex-col sm:ml-6">
                                    <div>
                                        <div class="flex justify-between">
                                            <h4 class="text-sm">
                                                <a href="#" class="font-medium text-gray-700 hover:text-gray-800">{{product.product.name}}</a>
                                            </h4>
                                            <p class="ml-4 text-sm font-medium text-gray-900">${{product.product.price}}</p>
                                        </div>
                                        <!--attributes go here-->
                                        {% comment %} <p class="mt-1 text-sm text-gray-500"><span class="font-bold">Qty {{product.quantity}}</span></p> {% endcomment %}
                                        
                                        
                                    </div>
                                    
                                    <div class="mt-4 flex flex-1 items-end justify-between">
                                        <p class="flex items-center space-x-2 text-sm text-gray-700">
                                            <!-- Heroicon name: mini/check -->
                                            <svg class="h-5 w-5 flex-shrink-0 text-green-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                                <path fill-rule="evenodd" d="M16.704 4.153a.75.75 0 01.143 1.052l-8 10.5a.75.75 0 01-1.127.075l-4.5-4.5a.75.75 0 011.06-1.06l3.894 3.893 7.48-9.817a.75.75 0 011.05-.143z" clip-rule="evenodd" />
                                            </svg>
                                            <span>In stock</span>
                                        </p>
                                        <div class="ml-4">
                                            <a href="{% url 'products:remove_from_cart' pk=product.product.id %}">
                                                <button type="button" class="text-sm font-medium text-green-600 hover:text-green-500">
                                                    <span>Remove</span>
                                                </button>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <!--</form>-->
                            </li>
                        </form>
                        
                        <!-- More products... -->
                        {% endfor %}
                            <div class="mt-10">
                            <a href="{% url 'products:checkout' %}">
                                <button type="submit" class="w-full rounded-md border border-transparent bg-green-600 py-3 px-4 text-base font-medium text-white shadow-sm hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2 focus:ring-offset-gray-50">Checkout</button>
                                </a>  
                            </div>
                            
                            <div class="mt-6 text-center text-sm">
                                <p>
                                    or
                                    <a href="{% url 'products:list' %}" class="font-medium text-green-600 hover:text-green-500">
                                        Continue Shopping
                                        <span aria-hidden="true"> &rarr;</span>
                                    </a>
                                </p>
                            </div>
                            {% else %}
                            <div class="border-b border-gray-200 pb-5 mt-10">
                                <h3 class="text-lg font-medium leading-6 text-gray-900">Your cart is empty.
                                    <a href="{% url 'products:list' %}" class="font-medium text-green-600 hover:text-green-500 mt-3">
                                        Continue Shopping
                                    </a>
                                </h3>
                            </div>
                            
                            {% endif %}
                        </ul>
                    </section>
                    
                    
                </div>
            </div>
            {% else %}
            
            <div class="bg-white">
                <div class="mx-auto max-w-2xl py-16 px-4 sm:py-24 sm:px-6 lg:px-0">
                    <h1 class="text-center text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Shopping Cart</h1>
                    
                    <form class="mt-12">
                        <section aria-labelledby="cart-heading">
                            <h2 id="cart-heading" class="sr-only">Items in your shopping cart</h2>
                            
                            <ul role="list" class="divide-y divide-gray-200 border-t border-b border-gray-200">
                        
                                {% if products %}
                                {% for product in products %}
                                <li class="flex py-6">
                                    <div class="flex-shrink-0 bg-red-300">
                                        {% with product.product_image.all|first as image%}
                                        <img src="{{ image.url.url }}" alt="{{ image.alt_text }}" class="h-24 w-24 rounded-md object-cover object-center sm:h-32 sm:w-32">
                                        {% endwith %}
                                    </div>
                                    
                                    <div class="ml-4 flex flex-1 flex-col sm:ml-6">
                                        <div>
                                            <div class="flex justify-between">
                                                <h4 class="text-sm">
                                                    <a href="#" class="font-medium text-gray-700 hover:text-gray-800">{{product.name}}</a>
                                                </h4>
                                                <p class="ml-4 text-sm font-medium text-gray-900">${{product.price}}</p>
                                            </div>
                                            <!--attributes go here-->
                                            <p class="mt-1 text-sm text-gray-500">Mint</p>
                                            <p class="mt-1 text-sm text-gray-500">Medium</p>
                                        </div>
                                        
                                        <div class="mt-4 flex flex-1 items-end justify-between">
                                            <p class="flex items-center space-x-2 text-sm text-gray-700">
                                                <!-- Heroicon name: mini/check -->
                                                <svg class="h-5 w-5 flex-shrink-0 text-green-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                                    <path fill-rule="evenodd" d="M16.704 4.153a.75.75 0 01.143 1.052l-8 10.5a.75.75 0 01-1.127.075l-4.5-4.5a.75.75 0 011.06-1.06l3.894 3.893 7.48-9.817a.75.75 0 011.05-.143z" clip-rule="evenodd" />
                                                </svg>
                                                <span>In stock</span>
                                            </p>
                                            
                                            <div class="ml-4">
                                                <a href="{% url 'products:remove_from_cart' pk=product.id %}">
                                                    <button type="button" class="text-sm font-medium text-green-600 hover:text-green-500">
                                                        <span>Remove</span>
                                                    </button>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                
                                
                                <!-- More products... -->
                                {% endfor %}
                                <div class="mt-10">
                                    <a href="{% url 'products:checkout' %}">
                                        <button type="submit" class="w-full rounded-md border border-transparent bg-green-600 py-3 px-4 text-base font-medium text-white shadow-sm hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2 focus:ring-offset-gray-50">Checkouts</button>
                                        </a>  
                                    </div>
                                    
                                    <div class="mt-6 text-center text-sm">
                                        <p>
                                            or
                                            <a href="{% url 'products:list' %}" class="font-medium text-green-600 hover:text-green-500">
                                                Continue Shopping
                                                <span aria-hidden="true"> &rarr;</span>
                                            </a>
                                        </p>
                                    </div>
                                    {% else %}
                                    <div class="border-b border-gray-200 pb-5 mt-10">
                                        <h3 class="text-lg font-medium leading-6 text-gray-900">Your cart is empty.
                                            <a href="{% url 'products:list' %}" class="font-medium text-green-600 hover:text-green-500 mt-3">
                                                Continue Shopping
                                            </a>
                                        </h3>
                                    </div>
                                    {% endif %}
                                </ul>
                            </section>
                          
                        </form>
                    </div>
                </div>
                {% endif %}          
{% endblock %}
            

templates/store/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="relative bg-gray-900">
    <!-- Decorative image and overlay -->
    <div aria-hidden="true" class="absolute inset-0 overflow-hidden">
      <img src="{% static 'af1_black.webp' %}" alt="" class="h-full w-full object-cover object-center">
    </div>
    <div aria-hidden="true" class="absolute inset-0 bg-gray-900 opacity-40"></div>
    <div class="relative mx-auto flex max-w-3xl flex-col items-center py-32 px-6 text-center sm:py-64 lg:px-0">
        <h1 class="text-4xl font-bold tracking-tight text-white lg:text-6xl">New arrivals are here</h1>
        <p class="mt-4 text-xl text-white">The new arrivals have, well, newly arrived. Check out the latest options from our summer small-batch release while they're still in stock.</p>
        <a href="#" class="mt-8 inline-block rounded-md border border-transparent bg-white py-3 px-8 text-base font-medium text-gray-900 hover:bg-gray-100">Shop New Arrivals</a>
    </div>

</div>
<section aria-labelledby="collection-heading" class="mx-auto max-w-xl px-4 pt-24 sm:px-6 sm:pt-32 lg:max-w-7xl lg:px-8">
    <h2 id="collection-heading" class="text-2xl font-bold tracking-tight text-gray-900">Shop by Collection</h2>
    <p class="mt-4 text-base text-gray-500">Each season, we collaborate with world-class designers to create a collection inspired by the natural world.</p>

    <div class="mt-10 space-y-12 lg:grid lg:grid-cols-3 lg:gap-x-8 lg:space-y-0">
      <a href="#" class="group block">
        <div aria-hidden="true" class="aspect-w-3 aspect-h-2 overflow-hidden rounded-lg group-hover:opacity-75 lg:aspect-w-5 lg:aspect-h-6">
          <img src="{% static 'dop_kicks_2.jpeg' %}" alt="Brown leather key ring with brass metal loops and rivets on wood table." class="h-full w-full object-cover object-center">
        </div>
        <h3 class="mt-4 text-base font-semibold text-gray-900">The Overrated Js</h3>
        <p class="mt-2 text-sm text-gray-500">Michael Jordan is clearly not the GOAT but his shoes are the best out there.</p>
      </a>

      <a href="#" class="group block">
        <div aria-hidden="true" class="aspect-w-3 aspect-h-2 overflow-hidden rounded-lg group-hover:opacity-75 lg:aspect-w-5 lg:aspect-h-6">
          <img src="{% static 'dop_kicks_3.jpeg' %}" alt="Natural leather mouse pad on white desk next to porcelain mug and keyboard." class="h-full w-full object-cover object-center">
        </div>
        <h3 class="mt-4 text-base font-semibold text-gray-900">Summer Friendly</h3>
        <p class="mt-2 text-sm text-gray-500">The summer is the perfect time to put these on and hit the streets.</p>
      </a>

      <a href="#" class="group block">
        <div aria-hidden="true" class="aspect-w-3 aspect-h-2 overflow-hidden rounded-lg group-hover:opacity-75 lg:aspect-w-5 lg:aspect-h-6">
          <img src="{% static 'dop_kicks.jpeg' %}" alt="Person placing task list card into walnut card holder next to felt carrying case on leather desk pad." class="h-full w-full object-cover object-center">
        </div>
        <h3 class="mt-4 text-base font-semibold text-gray-900">Dope Kicks</h3>
        <p class="mt-2 text-sm text-gray-500">These sneakers will enhance your jumper. You won't admit it but you have been struggling with your jumper for a while now.</p>
      </a>
    </div>
  </section>

      <!-- Featured section -->
      <section aria-labelledby="social-impact-heading" class="mx-auto max-w-7xl px-4 pt-24 sm:px-6 sm:pt-32 lg:px-8">
        <div class="relative overflow-hidden rounded-lg">
          <div class="absolute inset-0">
            <img src="{% static 'af1_black.webp' %}" alt="" class="h-full w-full object-cover object-center">
          </div>
          <div class="relative bg-gray-900 bg-opacity-40 py-32 px-6 sm:py-40 sm:px-12 lg:px-16">
            <div class="-mb-24 sm:-mb-0 relative mx-auto flex max-w-3xl flex-col items-center text-center">
              <h2 id="social-impact-heading" class="text-3xl font-bold tracking-tight text-white sm:text-4xl">
                <span class="block sm:inline">Level up</span>
                <span class="block sm:inline">your game</span>
              </h2>
              <p class="mt-3 text-xl text-white">Make the homies jealous at the next meetup. Wear these with the utmost confidence and let everyone know that your feet are on fire because you have the GOAT kicks on - Air Force 1.</p>
              <a href="#" class="mt-8 block w-full rounded-md border border-transparent bg-white py-3 px-8 text-base font-medium text-gray-900 hover:bg-gray-100 sm:w-auto">Shop Air Force 1s</a>
            </div>
          </div>
        </div>
      </section>
{% endblock %}